function AbaqusShellGeo(node,face,name)
% Multiscale Homogenization Code for Periodic Lattice Metamaterial
% Jin BO, Email:kinpoer@nuaa.edu.cn
%% Shell geometries(.inp file in Abaqus)
% Adjust the position of the lattice structure
cmax = max(node);cmin = min(node);dc = cmax-cmin;
cmean = mean([cmax;cmin]);
dx = dc(1);dy = dc(2);dz = dc(3);
refp = cmean;
vector = [0 dy/2 0] - refp;
node = MovePAlongV(node, vector);
fileName = strcat(name,'.inp');
fidDeal = fopen(fileName,'wt');
% Head keyword
fprintf(fidDeal,['*Heading\n' ...
'** Job name: T Model name: T\n' ...
'** Generated by: Abaqus/CAE 2021\n' ...
'*Preprint, echo=NO, model=NO, history=NO, contact=NO\n' ...
'**\n']);
% Node keyword
fprintf(fidDeal,['** PARTS\n' ...
'**\n' ...
'*Part, name=SHELL\n' ...
'*Node\n']);
for i=1:1:length(node)
    fprintf(fidDeal,'%d, %.5f, %.5f, %.5f\n',i,node(i,1),node(i,2),node(i,3));
end
% Element keyword
fprintf(fidDeal,'*Element, type=S3\n');
for i=1:1:length(face)
    fprintf(fidDeal,'%d, %d, %d, %d\n',i,face(i,1),face(i,2),face(i,3));
end
fprintf(fidDeal,'*Elset, elset=ALLELE, generate\n');
fprintf(fidDeal,'1,%d,1\n',length(face));
fprintf(fidDeal,'*End Part');
fclose(fidDeal);
end
